def finding_motif(dna_str, sub_str):
    """
    Generator used to find every occurrency of t as s.

    Parameters
    ----------
    dna_str: str
    sub_str: str

    Returns
    -------
    All locations of t as a substring of s.
    """
    start = 0
    while True:
        start = dna_str.find(sub_str, start)
        if start == -1: return
        yield str(start + 1)
        start += 1


if __name__ == '__main__':
    dna = 'AGGCCTGATTACTGATTACTGATTAGGCTGATTAACCAGTCTGATTACTGATTATCGCTGATTAAGGACATGGCTGATTACTGATTAGACTGATTATTCGCTGATTAGCGACTAGGAGCTGATTAATCTGATTAACTGATTAGCTGATTAGCTCTGATTACTCTGATTAACTGATTACTGATTACGGAGGCGTCCTGATTACCTGATTAAGTGCTGATTAACTGATTATCTTCTGATTACTCCTGATTACCTGATTACTGATTATCTGATTATCTTCGTTCCGATATCTAGCTGATTAACCTGATTACTGATTACTGATTACTGATTATCCGACCTGATTAGACTGCTGATTATCTGATTAACTGATTATCGGATGCCTGATTAATCTGATTAATGCTAAGCCCTGATTATCTCTGATTACTGATTACTCTTCCTGATTACGTTAGCTGATTAATATAGGCTCTGATTAACTGATTAGACACTGATTACCACAGCAAATTGCCCTGATTATTTAACTGTCTGATTACTGATTACAAGACTGATTAGGCTTGAACGCGCGCTGATTACGCTGATTACCAGCTGATTACACGGGCTGATTAAAAAGACGCCTGATTACTCCTGATTAGCTGATTACTGATTAAGAACAATGGGCTGATTATTAACTGATTACTGATTAACTGATTAGGTCTGACACTGATTAGCACTGATTACTGATTACTGATTACTGATTATCGACTGATTAGCCTGATTACGCTGATTACGCTGATTAAGCCTGATTAACTGATTACTGATTAGTCTGATTACTGATTACTGATTATTCACGATACTGATTACTGATTAATCTGATTACACCTGATTACTGATTACGGCTGATTACCTGATTACTGATTACTGATTAGACCTGATTA'
    search = 'CTGATTACT'

    indexes = list(finding_motif(dna, search))
    print(' '.join(indexes))
